<?php

/** Request
 * 功能描述：简历操作 算法字段更新
 */
require_once './public.php';
$json='{
    "request": {
        "c": "resumes/logic_resume",
        "m": "save",
        "p": {
            "training": [],
            "language": {
                "1498719676": {
                    "certificate": "",
                    "name": "英语",
                    "level": "",
                    "updated_at": "2017-06-29 15:01:16",
                    "created_at": "2017-06-29 15:01:16",
                    "id": "1498719676"
                }
            },
            "certificate": {
                "1498719676": {
                    "start_time": "",
                    "name": "全国计算机软件技术资格与水平考试",
                    "description": "",
                    "updated_at": "2017-06-29 15:01:16",
                    "created_at": "2017-06-29 15:01:16",
                    "id": "1498719676"
                },
                "1498719677": {
                    "start_time": "",
                    "name": "其他内容",
                    "description": "",
                    "updated_at": "2017-06-29 15:01:16",
                    "created_at": "2017-06-29 15:01:16",
                    "id": "1498719677"
                },
                "1498719678": {
                    "start_time": "",
                    "name": "掌握SQL、JDBC等数据库访问技术，有较丰富的常用主流数据库应用开发经验",
                    "description": "",
                    "updated_at": "2017-06-29 15:01:16",
                    "created_at": "2017-06-29 15:01:16",
                    "id": "1498719678"
                },
                "1498719679": {
                    "start_time": "",
                    "name": "熟悉J2ee、B/S三层架构，熟练掌握 JSP,Web Servlet,Xml理解和掌握Struts、Spring、Ibatis,Hibernate等 常用的JAVA框架，并应用框架进行项目开发，有分布式系统开发经验",
                    "description": "",
                    "updated_at": "2017-06-29 15:01:16",
                    "created_at": "2017-06-29 15:01:16",
                    "id": "1498719679"
                },
                "1498719680": {
                    "start_time": "",
                    "name": "熟练掌握oracle,sql server,mysql,redis,memcache数据库熟练使用SQL语句，写存储过程",
                    "description": "",
                    "updated_at": "2017-06-29 15:01:16",
                    "created_at": "2017-06-29 15:01:16",
                    "id": "1498719680"
                },
                "1498719681": {
                    "start_time": "",
                    "name": "熟练掌握EXTJS、XHTML、CSS、Javascript和AJAX等前端页面开发技术",
                    "description": "",
                    "updated_at": "2017-06-29 15:01:16",
                    "created_at": "2017-06-29 15:01:16",
                    "id": "1498719681"
                },
                "1498719682": {
                    "start_time": "",
                    "name": "熟练掌握selenium+junit做自动化测试",
                    "description": "",
                    "updated_at": "2017-06-29 15:01:16",
                    "created_at": "2017-06-29 15:01:16",
                    "id": "1498719682"
                },
                "1498719683": {
                    "start_time": "",
                    "name": "依据项目需求及总体架构设计方案，完成软件功能模块的设计、编码，编写符合规范的设计开发文档、数据库结构设计文档等，对软件项目进行技术升级和改造，对大数据表做性能速度优化处理。ERP实施和可以沟通了解需求，把控开发进度，开发时间，维护系统的正常运行，优化代码执行效率速度，对数据量较大的一些视图查询速度提供解决方案并实施，培训用户使用系统，会linux基本操作，可以做集群，负载均衡等。",
                    "description": "",
                    "updated_at": "2017-06-29 15:01:16",
                    "created_at": "2017-06-29 15:01:16",
                    "id": "1498719683"
                }
            },
            "pattern": "Unknown",
            "work": {
                "1498719676": {
                    "start_time": "2011年03月",
                    "end_time": "2013年03月",
                    "so_far": "N",
                    "corporation_name": "国研软件",
                    "industry_name": "",
                    "architecture_name": "",
                    "position_name": "",
                    "title_name": "",
                    "station_name": "",
                    "reporting_to": "",
                    "subordinates_count": "0",
                    "responsibilities": "2011032013-03 \r\n国研软件 \r\n( 2年 ) \r\n研发部 \r\n工作描述： \r\n掌握SQL、JDBC等数据库访问技术，有较丰富的常用主流数据库应用开发经验； \r\n熟悉J2ee、B/S三层架构，熟练掌握 JSP,Web Servlet,Xml理解和掌握Struts、Spring、Ibatis,Hibernate等 常用的JAVA框架，并应用框架进行项目开发； \r\n熟练掌握oracle,sql server,mysql数据库，熟练使用SQL语句; \r\n熟练掌握EXTJS、XHTML、CSS、Javascript、Jquery和AJAX等前端页面开发技术。 \r\n熟练ASP.Net(C#)开发 \r\n",
                    "management_experience": "N",
                    "work_type": "",
                    "basic_salary": "",
                    "bonus": "",
                    "annual_salary": "",
                    "basic_salary_from": "",
                    "basic_salary_to": "",
                    "salary_month": "",
                    "annual_salary_from": "",
                    "annual_salary_to": "",
                    "corporation_desc": "",
                    "scale": "",
                    "city": "",
                    "corporation_type": "",
                    "reason": "",
                    "is_oversea": "",
                    "achievement": "",
                    "a_p_b": "",
                    "updated_at": "2017-06-29 15:01:16",
                    "is_deleted": "N",
                    "corporation_id": "0",
                    "industry_ids": "0",
                    "created_at": "2017-06-29 15:01:16",
                    "id": "1498719676"
                },
                "1498719677": {
                    "start_time": "2013年07月",
                    "end_time": "2015年02月",
                    "so_far": "N",
                    "corporation_name": "金融公司",
                    "industry_name": "",
                    "architecture_name": "",
                    "position_name": "软件研发工程师",
                    "title_name": "",
                    "station_name": "",
                    "reporting_to": "",
                    "subordinates_count": "0",
                    "responsibilities": "工作描述：负责前台页面开发，使用的是extjs（mvc）模式，后台框架用spring（mvc），主要做各种导入倒出数据转换和生成财务指令，生成动态word文档，excel解析拆分合并，各种贷款相关业务流程开发，优化流程，速度，代码量。协助同事完成一些开发工作。 \r\n",
                    "management_experience": "N",
                    "work_type": "",
                    "basic_salary": "100",
                    "bonus": "",
                    "annual_salary": "",
                    "basic_salary_from": "",
                    "basic_salary_to": "",
                    "salary_month": "",
                    "annual_salary_from": "",
                    "annual_salary_to": "",
                    "corporation_desc": "",
                    "scale": "",
                    "city": "",
                    "corporation_type": "",
                    "reason": "",
                    "is_oversea": "",
                    "achievement": "",
                    "a_p_b": "",
                    "updated_at": "2017-06-29 15:01:16",
                    "is_deleted": "N",
                    "corporation_id": "0",
                    "industry_ids": "0",
                    "created_at": "2017-06-29 15:01:16",
                    "id": "1498719677"
                }
            },
            "project": [],
            "basic": {
                "name": "李曜君",
                "resume_name": "",
                "gender": "M",
                "birth": "1993年09月",
                "nation": "",
                "degree": "1",
                "school_name": "中央财经大学",
                "discipline_name": "电子信息科学与技术",
                "corporation_name": "金融公司",
                "corporation_id": "0",
                "industry_name": "",
                "architecture_name": "",
                "work_type": "",
                "position_name": "软件研发工程师",
                "station_name": "",
                "start_time": "2013年07月",
                "marital": "U",
                "is_fertility": "U",
                "is_house": "U",
                "live_family": "U",
                "account_province": "26",
                "account": "26",
                "address_province": "0",
                "address": "0",
                "focused_corporations": "",
                "focused_feelings": "",
                "basic_salary": "10",
                "salary_month": "",
                "basic_salary_from": "",
                "basic_salary_to": "",
                "annual_salary": "",
                "annual_salary_from": "",
                "annual_salary_to": "",
                "bonus": "",
                "management_experience": "N",
                "work_experience": "72",
                "current_status": "2",
                "is_core": "N",
                "src": "100",
                "resume_cnt": "1",
                "remark": "",
                "customization": "",
                "status": "CVC",
                "is_add_v": "N",
                "locked_time": "0",
                "is_author": "O",
                "expect_city_ids": "124",
                "expect_city_names": "北京",
                "expect_salary_from": "25",
                "expect_salary_to": "25",
                "expect_salary_month": "",
                "expect_annual_salary_from": "300",
                "expect_annual_salary_to": "300",
                "expect_annual_salary": "",
                "expect_bonus": "",
                "expect_work_at": "",
                "expect_type": "",
                "expect_position_name": "高级软件工程师 软件研发工程师",
                "expect_industry_name": "计算机软件 IT服务 系统 数据 维护 网络游戏 互联网 电子商务",
                "expect_remarks": "",
                "not_expect_corporation_name": "",
                "is_validate": "U",
                "is_increased": "Y",
                "is_active": "U",
                "bonus_text": "",
                "options": "",
                "other_welfare": "",
                "category": "",
                "resume_updated_at": "0000-00-00 00:00:00",
                "updated_at": "2017-06-29 15:01:16",
                "verification_at": "0",
                "interests": "",
                "overseas": "N",
                "political_status": "",
                "project_info": "",
                "other_info": "",
                "card": "",
                "speciality": "",
                "phone_id": "2C22D4FB15CD7390D8613E61",
                "mail_id": "D3DF0546AAE72B516FA56C69288C60C7",
                "practice": "",
                "study": "",
                "text": "",
                "self_remark": "",
                "nation_id": "0",
                "photo": "",
                "my_project": "",
                "not_expect_corporation_ids": "",
                "age": "24",
                "id": "6271125",
                "src_no": "",
                "is_deleted": "N",
                "user_id": "0",
                "is_private": "0",
                "so_far": "N",
                "discipline_desc": "",
                "end_time": "2015年02月",
                "is_entrance": "Y",
                "created_at": "2017-06-06 14:58:13",
                "subordinates_count": "0",
                "city": "",
                "scale": "",
                "responsibilities": "工作描述：负责前台页面开发，使用的是extjs（mvc）模式，后台框架用spring（mvc），主要做各种导入倒出数据转换和生成财务指令，生成动态word文档，excel解析拆分合并，各种贷款相关业务流程开发，优化流程，速度，代码量。协助同事完成一些开发工作。 \r\n",
                "reporting_to": "",
                "corporation_type": "",
                "corporation_desc": "",
                "has_phone": "N",
                "attachment_ids": "",
                "industry_ids": "",
                "title_name": "",
                "reason": "",
                "is_oversea": "",
                "achievement": "",
                "a_p_b": ""
            },
            "skill": [],
            "education": {
                "1498719676": {
                    "start_time": "2015年09月",
                    "end_time": "",
                    "school_name": "中央财经大学",
                    "discipline_name": "电子信息科学与技术",
                    "degree": "1",
                    "so_far": "Y",
                    "is_entrance": "Y",
                    "discipline_desc": "",
                    "updated_at": "2017-06-29 15:01:16",
                    "created_at": "2017-06-29 15:01:16",
                    "id": "1498719676"
                },
                "1498719677": {
                    "start_time": "2011年01月",
                    "end_time": "2013年07月",
                    "school_name": "北京电子科技学院",
                    "discipline_name": "",
                    "degree": "4",
                    "so_far": "N",
                    "is_entrance": "Y",
                    "discipline_desc": "",
                    "updated_at": "2017-06-29 15:01:16",
                    "created_at": "2017-06-29 15:01:16",
                    "id": "1498719677"
                }
            },
            "user_tag": [],
            "setting": {
                "salary_is_visible": "1"
            },
            "verification": [],
            "is_toc": "0",
            "map": {
                "2590899": {
                    "src": "100",
                    "src_no": "6271125",
                    "show_src": "100",
                    "show_src_no": "6271125",
                    "is_deleted": "N",
                    "updated_at": "2017-06-06 14:59:48",
                    "created_at": "2017-06-06 14:58:13"
                }
            },
            "algorithm": {
                "updated_at": "2017-06-06 14:58:13",
                "created_at": "2017-06-06 14:58:13",
                "cv_source": "",
                "cv_trade": "",
                "cv_title": "",
                "cv_tag": "",
                "cv_entity": "",
                "cv_education": "",
                "cv_feature": "",
                "skill_tag": "",
                "personal_tag": "",
                "diff": "[]",
                "cv_quality": "",
                "cv_language": "",
                "cv_degree": "99",
                "cv_resign": ""
            },
            "contact": {
                "name": "李曜君",
                "tel": "13691560737",
                "phone": "13691560737",
                "email": "279613634@qq.com",
                "qq": "279613634",
                "msn": "",
                "sina": "",
                "ten": "",
                "wechat": "",
                "phone_area": "1",
                "is_deleted": "N",
                "updated_at": "2017-06-06 14:59:47",
                "created_at": "2017-06-06 14:58:13"
            },
            "source": {
                "src": 100
            }
        }
    },
    "header": {
        "client_ip": "127.0.0.1",
        "local_ip": "127.0.0.1",
        "log_id": "3900112915",
        "user_ip": "127.0.0.1",
        "ip": "127.0.0.1",
        "version": 1,
        "signid": "3900122834",
        "provider": "2b",
        "auth": "2b",
        "product_name": "tob_web",
        "session_id": "0021fve9qbsuss2i8ilu90g7i3",
        "uid": "81",
        "uname": "cage1618@qq.com",
        "appid": "5",
        "unique": "39001129153900136076"
    }
}';
$param = json_decode($json,true);
$param['request']['w']='icdc_basic';
echo client($param);

/** Response
 *{
 *   "response": {
 *       "err_no": 0,
 *       "err_msg": "",
 *       "results": "Refresh success....."
 *   }
 *}
 */
